import Foundation

/// Remote plaintext can override these bundled game strings.
enum HouseRocketsLocalization {
    static func value(for key: String, language: String?) -> String? {
        guard let copy = values[key] else { return nil }
        return language?.lowercased().hasPrefix("en") == true ? copy.en : copy.tr
    }

    private static let values: [String: (tr: String, en: String)] = [
        "games_house_rockets_title": ("House Rockets", "House Rockets"),
        "games_house_rockets_card_description": ("Roketini yönlendir, engelleri aş ve son kalan ol.", "Guide your rocket past obstacles and be the last one flying."),
        "games_house_rockets_badge": ("ROKET YARIŞI", "ROCKET RACE"),
        "house_rockets_title": ("House Rockets", "House Rockets"),
        "house_rockets_subtitle": ("Sen pilot koltuğunda, rakiplerin bot.", "You’re the pilot. Your rivals are bots."),
        "house_rockets_mode_prompt": ("Uçuşa nasıl katılmak istersin?", "How would you like to fly?"),
        "house_rockets_mode_bots": ("Botlarla oyna", "Play with bots"),
        "house_rockets_mode_bots_detail": ("1–3 yerel bota karşı yarış. İnternet gerekmez.", "Race against 1–3 local bots. No internet needed."),
        "house_rockets_mode_housemates": ("Ev arkadaşlarınla oyna", "Play with housemates"),
        "house_rockets_mode_housemates_detail": ("Aynı evin gerçek üyeleriyle çevrim içi yarış. Bu modda bot yok.", "Race online with real members of your house. This mode has no bots."),
        "house_rockets_change_mode": ("Modu değiştir", "Change mode"),
        "house_rockets_offline": ("Bu cihazda, internetsiz oynanır", "Play offline on this device"),
        "house_rockets_online_unavailable": ("Çevrim içi oyun kullanılamıyor", "Online play unavailable"),
        "house_rockets_online_unavailable_detail": ("Bu sürümde çevrim içi oyun bağlantısı henüz hazır değil. Modu değiştirerek botlarla oynayabilirsin.", "Online play is not connected in this version yet. Change mode to play with bots."),
        "house_rockets_online_sign_in": ("Ev arkadaşlarınla oynamak için oturum açman gerekiyor.", "Sign in to play with your housemates."),
        "house_rockets_online_house_required": ("Ev arkadaşlarınla oynamak için önce bir ev seçmen gerekiyor.", "Select a house to play with your housemates."),
        "house_rockets_member": ("Ev üyesi", "House member"),
        "house_rockets_ready": ("Hazır", "Ready"),
        "house_rockets_waiting": ("Bekliyor", "Waiting"),
        "house_rockets_ready_action": ("Yatay ekrana geç ve hazır ol", "Enter landscape and get ready"),
        "house_rockets_not_ready_action": ("Hazır durumundan çık", "Not ready"),
        "house_rockets_ready_count": ("{ready}/{total} kişi hazır", "{ready}/{total} players ready"),
        "house_rockets_ready_deadline": ("Hazırlık penceresi: {seconds} sn", "Ready window: {seconds}s"),
        "house_rockets_online_countdown": ("Uçuşa {seconds} sn", "Launching in {seconds}s"),
        "house_rockets_online_ready_detail": ("Hazır olmadan önce ekran yataya döner. Uçuş, ev arkadaşların da hazır olduğunda sunucu tarafından başlatılır.", "Your screen rotates before you become ready. The server launches the flight when your housemates are ready too."),
        "house_rockets_online_connecting": ("Evin lobisine bağlanılıyor", "Connecting to your house lobby"),
        "house_rockets_online_connecting_detail": ("Ev arkadaşlarınla aynı uçuş oturumu hazırlanıyor.", "Preparing the shared flight session for your housemates."),
        "house_rockets_online_lobby": ("Evin uçuş lobisi", "Your house flight lobby"),
        "house_rockets_online_lobby_detail": ("Uçuş için en az {minimum} kişi hazır olmalı. Ev arkadaşların bu modu seçerek aynı lobiye katılabilir.", "At least {minimum} players must be ready. Your housemates can join this lobby by choosing this mode."),
        "house_rockets_online_joining": ("Lobiye katılınıyor", "Joining the lobby"),
        "house_rockets_online_confirming": ("Sunucu onayı bekleniyor", "Waiting for server confirmation"),
        "house_rockets_online_launching": ("Uçuşa hazırlanılıyor", "Preparing for launch"),
        "house_rockets_online_launching_detail": ("Ekranı yatay tut. Uçuş birlikte başlayacak.", "Keep your screen landscape. The flight will start together."),
        "house_rockets_online_waiting_start": ("Başlangıç bekleniyor", "Waiting for launch"),
        "house_rockets_online_flying": ("Canlı uçuş", "Live flight"),
        "house_rockets_online_waiting_control": ("Yönlendirme hazırlanıyor", "Preparing controls"),
        "house_rockets_online_eliminated": ("{names} elendi", "{names} eliminated"),
        "house_rockets_online_syncing_lobby": ("Lobi güncelleniyor…", "Syncing the lobby…"),
        "house_rockets_online_syncing_flight": ("Uçuş durumu alınıyor…", "Syncing the flight…"),
        "house_rockets_online_finalizing": ("Sonuç kaydediliyor…", "Saving the result…"),
        "house_rockets_online_ended": ("Uçuş sona erdi", "Flight ended"),
        "house_rockets_online_ended_detail": ("Bu uçuş oturumu kapandı. Oyunlara dönebilirsin.", "This flight session has closed. You can return to games."),
        "house_rockets_online_connection_failed": ("Lobi bağlantısı kesildi", "Lobby connection failed"),
        "house_rockets_online_connection_failed_detail": ("Sunucuyla bağlantı kurulamadı. Bağlantını kontrol edip yeniden dene.", "Could not connect to the server. Check your connection and try again."),
        "house_rockets_online_retry_after": ("{seconds} sn sonra yeniden bağlan", "Reconnect in {seconds}s"),
        "house_rockets_online_retry": ("Yeniden bağlan", "Reconnect"),
        "house_rockets_online_timeout": ("Sunucudan zamanında yanıt alınamadı. Yeniden bağlanarak güncel lobiyi alabilirsin.", "The server did not respond in time. Reconnect to get the current lobby."),
        "house_rockets_online_full": ("Bu uçuş lobisi dolu. Sonraki uçuşa katılabilirsin.", "This flight lobby is full. You can join the next flight."),
        "house_rockets_online_ready_closed": ("Bu oturum artık katılım veya hazır durumunu değiştirme kabul etmiyor.", "This session no longer accepts joining or readiness changes."),
        "house_rockets_online_command_rejected": ("İşlem uygulanamadı. Lobinin güncel durumunu kontrol edip tekrar dene.", "The action could not be applied. Check the current lobby state and try again."),
        "house_rockets_online_rate_limited": ("Çok sık istek gönderildi. Biraz bekleyip yeniden dene.", "Too many requests. Wait a moment and try again."),
        "house_rockets_online_forbidden": ("Bu evin oyun oturumuna erişimin yok. Ev üyeliğini kontrol et.", "You cannot access this house game session. Check your house membership."),
        "house_rockets_online_room_unavailable": ("Bu oyun oturumu bulunamadı veya çevrim içi oyun şu anda kullanılamıyor.", "This game session was not found or online play is currently unavailable."),
        "house_rockets_online_busy": ("Oyun sunucusu şu anda meşgul. Biraz sonra yeniden dene.", "The game server is currently busy. Try again shortly."),
        "house_rockets_online_update_required": ("Bu oyun sürümü sunucuyla uyumlu değil. Uygulamayı güncelle.", "This game version is incompatible with the server. Update the app."),
        "house_rockets_leaving": ("Lobiden çıkılıyor…", "Leaving the lobby…"),
        "house_rockets_bot_count": ("Bot sayısı", "Number of bots"),
        "house_rockets_rule_aim": ("Sağ veya sol kenara dokunup sürükleyerek yön ver", "Touch and drag along either edge to steer"),
        "house_rockets_rule_drive": ("İtki sürekli açık; bıraktığında son yön korunur", "Thrust stays on; releasing keeps your heading"),
        "house_rockets_rule_fields": ("Mavi çift ok kısa süre hızlandırır; kırmızı fren yavaşlatır", "Blue double arrows briefly boost speed; red brakes slow you down"),
        "house_rockets_boost_active": ("Hız ×1,45", "Speed ×1.45"),
        "house_rockets_slow_active": ("Hız ×0,65", "Speed ×0.65"),
        "house_rockets_turn": ("Turn", "Turn"),
        "house_rockets_spectating_short": ("İzliyorsun", "Spectating"),
        "house_rockets_vertical_transition": ("Parkur yukarı dönüyor · Ekranı yatay tut", "Course turning upward · Keep your screen landscape"),
        "house_rockets_horizontal_transition": ("Parkur sağa dönüyor · Ekranı yatay tut", "Course turning right · Keep your screen landscape"),
        "house_rockets_rule_survive": ("Temas öldürmez. Liderin gerisinde ekran dışına düşme", "Contact is safe. Stay on screen behind the leader"),
        "house_rockets_landscape": ("Oyun yatay ekranda açılır.", "The game opens in landscape."),
        "house_rockets_landscape_error": ("Yatay moda geçilemedi. Cihazı çevirip yeniden dene.", "Couldn’t enter landscape. Rotate your device and try again."),
        "house_rockets_start": ("Uçuşu başlat", "Start flight"),
        "house_rockets_rotating": ("Pist hazırlanıyor…", "Preparing the course…"),
        "house_rockets_pause": ("Duraklat", "Pause"),
        "house_rockets_resume": ("Devam et", "Resume"),
        "house_rockets_paused": ("Uçuş duraklatıldı", "Flight paused"),
        "house_rockets_joystick": ("Yön çubuğu", "Steering joystick"),
        "house_rockets_joystick_hint": ("Ekranın sağ veya sol kenarına dokunup istediğin yöne sürükle. Yön çubuğu sürüklerken görünür, bıraktığında kaybolur ve son yön korunur. Erişilebilirlik ayarı yönü 15 derece değiştirir.", "Touch either edge and drag in the direction you want to fly. The joystick appears while dragging and disappears on release, keeping your heading. Accessibility adjustments turn by 15 degrees."),
        "house_rockets_you": ("Sen", "You"),
        "house_rockets_bot_one": ("Bot Nova", "Bot Nova"),
        "house_rockets_bot_two": ("Bot Mavi", "Bot Blue"),
        "house_rockets_bot_three": ("Bot Güneş", "Bot Sun"),
        "house_rockets_alive": ("Kalan {count}", "{count} left"),
        "house_rockets_time": ("Süre", "Time"),
        "house_rockets_countdown_go": ("UÇ!", "FLY!"),
        "house_rockets_eliminated": ("Roketin elendi", "Your rocket is out"),
        "house_rockets_bot_eliminated": ("{name} elendi", "{name} is out"),
        "house_rockets_spectating": ("Botların yarışını izliyorsun", "Watching the remaining bots"),
        "house_rockets_won": ("Kazandın!", "You won!"),
        "house_rockets_lost": ("{name} kazandı", "{name} won"),
        "house_rockets_draw": ("Berabere", "Draw"),
        "house_rockets_result_detail": ("Son kalan roket yarışı aldı.", "The last rocket flying took the race."),
        "house_rockets_draw_detail": ("Son gemiler aynı anda ekranın gerisinde kaldı.", "The final rockets left the rear edge together."),
        "house_rockets_rematch": ("Yeniden oyna", "Play again"),
        "house_rockets_exit": ("Oyunlara dön", "Back to games"),
    ]
}
