import Foundation

/// Bundled demo copy keeps House-Tanks usable before the remote plaintext catalog is updated.
/// Remote values continue to take precedence in LocalizationStore.
enum HouseTanksLocalization {
    static func value(for key: String, language: String?) -> String? {
        guard let copy = values[key] else { return nil }
        return language?.lowercased().hasPrefix("en") == true ? copy.en : copy.tr
    }

    private static let values: [String: (tr: String, en: String)] = [
        "games_house_tanks_title": ("House-Tanks", "House-Tanks"),
        "games_house_tanks_card_description": ("Ateş et, basılı tutarak ilerle ve iki bota karşı ev arenasını ele geçir.", "Fire, hold to advance, and take the home arena from two bots."),
        "games_house_tanks_badge": ("1 OYUNCU · DEMO", "1 PLAYER · DEMO"),
        "house_tanks_title": ("House-Tanks", "House-Tanks"),
        "house_tanks_subtitle": ("Dokun, ateş et; basılı tut ve ilerle.", "Press to fire; hold to advance."),
        "house_tanks_demo_badge": ("DEMO", "DEMO"),
        "house_tanks_mode_title": ("Oyun modu", "Game mode"),
        "house_tanks_demo_mode": ("Botlarla oyna", "Play with bots"),
        "house_tanks_demo_mode_detail": ("Sen ve iki bot, üç galibiyetlik kısa bir maçta karşı karşıya.", "You and two bots face off in a race to three round wins."),
        "house_tanks_online_mode": ("Online oda", "Online room"),
        "house_tanks_online_mode_detail": ("Gerçek oyunculu odalar sonraki sürümde açılacak.", "Rooms with real players will arrive in a later release."),
        "house_tanks_soon": ("YAKINDA", "SOON"),
        "house_tanks_setup_title": ("Maç ayarları", "Match setup"),
        "house_tanks_color": ("Tank rengin", "Your tank color"),
        "house_tanks_color_teal": ("Turkuaz", "Teal"),
        "house_tanks_color_orange": ("Turuncu", "Orange"),
        "house_tanks_color_blue": ("Mavi", "Blue"),
        "house_tanks_difficulty": ("Bot zorluğu", "Bot difficulty"),
        "house_tanks_difficulty_easy": ("Kolay", "Easy"),
        "house_tanks_difficulty_normal": ("Normal", "Normal"),
        "house_tanks_difficulty_hard": ("Zor", "Hard"),
        "house_tanks_roster": ("Arena kadrosu", "Arena roster"),
        "house_tanks_you": ("Sen", "You"),
        "house_tanks_bot_one": ("Bot Atlas", "Bot Atlas"),
        "house_tanks_bot_two": ("Bot Nova", "Bot Nova"),
        "house_tanks_human_role": ("OYUNCU", "PLAYER"),
        "house_tanks_bot_role": ("BOT", "BOT"),
        "house_tanks_rules_title": ("Nasıl oynanır?", "How to play"),
        "house_tanks_rule_fire": ("Dokun ve ateş et", "Tap and fire"),
        "house_tanks_rule_fire_detail": ("Tankın sürekli döner. Dokunduğunda namlu yönünde ateş eder.", "Your tank rotates continuously. Tap to fire in the barrel direction."),
        "house_tanks_rule_drive": ("Basılı tut ve ilerle", "Hold to advance"),
        "house_tanks_rule_drive_detail": ("Basış başladığında dönüş kilitlenir. Parmağın ekrandayken tank namlu yönünde ilerler.", "Pressing locks your aim. Keep holding to drive in the barrel direction."),
        "house_tanks_rule_survive": ("Son kalan kazanır", "Last tank standing"),
        "house_tanks_rule_survive_detail": ("Beş zırhını koru ve üç turu ilk kazanan ol.", "Protect five armor points and be first to win three rounds."),
        "house_tanks_landscape_title": ("Yatay ekran gerekli", "Landscape required"),
        "house_tanks_landscape_detail": ("Maç başladığında ekran yatay moda geçer ve oyun bitene kadar orada kalır.", "The screen rotates when the match begins and stays landscape until you leave."),
        "house_tanks_landscape_error": ("Yatay moda geçilemedi. Cihazını çevirip yeniden dene.", "Couldn’t enter landscape. Rotate your device and try again."),
        "house_tanks_start": ("Maçı başlat", "Start match"),
        "house_tanks_rotating": ("Arena hazırlanıyor…", "Preparing the arena…"),
        "house_tanks_pause": ("Oyunu duraklat", "Pause game"),
        "house_tanks_resume": ("Devam et", "Resume"),
        "house_tanks_paused": ("Arena duraklatıldı", "Arena paused"),
        "house_tanks_paused_detail": ("Tanklar ve süre bekliyor. Hazır olduğunda devam et.", "The tanks and timer are waiting. Resume when you’re ready."),
        "house_tanks_round": ("Tur {number}", "Round {number}"),
        "house_tanks_time": ("Süre", "Time"),
        "house_tanks_armor": ("Zırh", "Armor"),
        "house_tanks_round_score": ("Tur skoru", "Round score"),
        "house_tanks_tap_hint": ("Ateş etmek için dokun · İlerlemek için basılı tut", "Press to fire · Hold to advance"),
        "house_tanks_playfield_accessibility": ("House-Tanks oyun alanı", "House-Tanks playfield"),
        "house_tanks_playfield_hint": ("Etkinleştirince tank ateş eder ve kısa süre namlu yönünde ilerler.", "Activate to fire and briefly advance in the barrel direction."),
        "house_tanks_countdown_go": ("BAŞLA!", "GO!"),
        "house_tanks_round_won": ("Bu tur senin!", "You took the round!"),
        "house_tanks_round_lost": ("{name} turu aldı", "{name} took the round"),
        "house_tanks_round_draw": ("Tur berabere", "Round draw"),
        "house_tanks_round_won_detail": ("Atış açını koru; maç henüz bitmedi.", "Keep your firing line; the match isn’t over yet."),
        "house_tanks_round_lost_detail": ("Bir sonraki turda atış açını daha erken kur.", "Set your firing angle earlier in the next round."),
        "house_tanks_round_draw_detail": ("Kimse puan almadı. Aynı skorla yeni tur başlıyor.", "No one scored. A new round starts with the same score."),
        "house_tanks_next_round": ("Sonraki tur", "Next round"),
        "house_tanks_champion_you": ("Evin şampiyonu sensin!", "You rule the house!"),
        "house_tanks_champion_bot": ("{name} maçı kazandı", "{name} won the match"),
        "house_tanks_champion_detail": ("Üç tur galibiyetiyle arena tamamlandı.", "The arena is complete with three round wins."),
        "house_tanks_rematch": ("Rövanş oyna", "Play a rematch"),
        "house_tanks_exit": ("Oyunlara dön", "Back to games"),
    ]
}
