import Foundation

/// Bundled demo copy until these keys are supplied by the plaintext endpoint.
/// Remote translations always take precedence in LocalizationStore.
enum RPSLocalization {
    static func value(for key: String, language: String?) -> String? {
        guard let copy = values[key] else { return nil }
        return language?.lowercased().hasPrefix("en") == true ? copy.en : copy.tr
    }

    private static let values: [String: (tr: String, en: String)] = [
        "games_rps_title": ("Taş · Kağıt · Makas", "Rock · Paper · Scissors"),
        "games_rps_card_description": ("Hamleni seç, rakibini ele. 2–8 kişilik turnuvada kupaya uzan!", "Pick a move, win your duel. Chase the cup in a 2–8 player tournament!"),
        "games_rps_badge": ("2–8 KİŞİ · DEMO", "2–8 PLAYERS · DEMO"),
        "rps_demo": ("DEMO ARENASI", "DEMO ARENA"),
        "rps_hero": ("Üç hamle.\nTek şampiyon.", "Three moves.\nOne champion."),
        "rps_intro": ("Biraz sezgi, biraz şans.\nSon hamle senin olsun.", "A little instinct. A little luck.\nMake the last move yours."),
        "rps_demo_detail": ("Sen oynarsın, diğer oyuncuları demo yönetir.", "You play. The demo controls the other players."),
        "rps_players": ("ARENA KADROSU", "ARENA ROSTER"),
        "rps_count": ("{count}/8 oyuncu", "{count}/8 players"),
        "rps_you": ("Sen", "You"),
        "rps_local": ("SEN", "YOU"),
        "rps_bot": ("DEMO", "BOT"),
        "rps_name": ("Oyuncu adı", "Player name"),
        "rps_add": ("Oyuncu ekle", "Add player"),
        "rps_remove": ("{name} adlı oyuncuyu çıkar", "Remove {name}"),
        "rps_name_hint": ("2–8 oyuncu · Benzersiz isimler · En fazla 24 karakter", "2–8 players · Unique names · Up to 24 characters"),
        "rps_rules": ("ARENANIN KURALLARI", "ARENA RULES"),
        "rps_rule_duel": ("Kazanan yoluna devam eder", "Winners advance"),
        "rps_rule_duel_detail": ("Her tur eşleşmeler karıştırılır. Tek galibiyet üst tura taşır; beraberlikte maç tekrarlanır.", "Pairings shuffle each round. One win advances you; a tie repeats the duel."),
        "rps_rule_bye": ("Tek kalan, kurayla seçilir", "A random bye"),
        "rps_rule_bye_detail": ("Oyuncu sayısı tekse herkesin eşit şansı vardır. Kurayı kazanan, o turu maç yapmadan geçer.", "With an odd player count, everyone has an equal chance. The drawn player advances without a duel."),
        "rps_cycle": ("Taş makası kırar · Makas kağıdı keser · Kağıt taşı sarar", "Rock beats scissors · Scissors beat paper · Paper beats rock"),
        "rps_start": ("Kurayı çek, arenayı aç", "Draw the bracket"),
        "rps_close": ("Oyundan çık", "Leave game"),
        "rps_round": ("TUR {number}", "ROUND {number}"),
        "rps_final": ("BÜYÜK FİNAL", "GRAND FINAL"),
        "rps_draw_title": ("Eşleşmeler hazır.", "The stage is set."),
        "rps_draw_detail": ("Rakipler belli. Sıradaki hamle arenada.", "Rivals drawn. The next move is in the arena."),
        "rps_bye_label": ("KURAYLA ÜST TURDA", "ADVANCES BY DRAW"),
        "rps_bye_detail": ("Bu turun şanslı ismi. Maç yapmadan üst tura geçer.", "This round’s lucky player advances without a duel."),
        "rps_no_bye": ("Bu tur herkesin bir rakibi var.", "Everyone has an opponent this round."),
        "rps_enter": ("İlk düelloya geç", "Enter the first duel"),
        "rps_choose": ("Hamlen ne olacak?", "What’s your move?"),
        "rps_choice_detail": ("Bir hamleye dokun. Açılana kadar seçimler gizli.", "Tap a move. Both choices stay hidden until reveal."),
        "rps_spectator": ("Tribün sırası sende.", "You’re in the stands."),
        "rps_spectator_detail": ("Bu eşleşmeyi demo oynayacak. Düelloyu başlat ve sonucu izle.", "The demo plays this pairing. Start the duel and watch the reveal."),
        "rps_watch": ("Düelloyu izle", "Watch the duel"),
        "rps_locked": ("Hamleler kilitlendi.", "Moves locked in."),
        "rps_countdown_detail": ("Taş… Kağıt… Makas!", "Rock… Paper… Scissors!"),
        "rps_rock": ("Taş", "Rock"),
        "rps_paper": ("Kağıt", "Paper"),
        "rps_scissors": ("Makas", "Scissors"),
        "rps_hidden": ("Gizli hamle", "Hidden move"),
        "rps_tie": ("Aynı fikir, bir daha!", "Great minds think alike!"),
        "rps_tie_detail": ("Kimse elenmedi. Aynı rakipler, yeni hamleler.", "Nobody is eliminated. Same rivals, new moves."),
        "rps_winner": ("{name} kazandı!", "{name} wins!"),
        "rps_you_won": ("Kazandın!", "You win!"),
        "rps_win_detail": ("Bir rakip geride, kupa bir adım ileride.", "One rival down. One step closer to the cup."),
        "rps_attempt": ("EL {number}", "HAND {number}"),
        "rps_retry": ("Yeni hamle seç", "Play the tie again"),
        "rps_continue": ("Devam et", "Continue"),
        "rps_round_done": ("Bir adım daha yakın.", "One step closer."),
        "rps_advancing": ("ÜST TURA GEÇENLER", "ADVANCING PLAYERS"),
        "rps_next_round": ("Sıradaki turun kurasını çek", "Draw the next round"),
        "rps_show_champion": ("Şampiyonu kutla", "Celebrate the champion"),
        "rps_bracket": ("KUPAYA GİDEN YOL", "ROAD TO THE CUP"),
        "rps_pending": ("Bekliyor", "Pending"),
        "rps_duel": ("Düello {number}", "Duel {number}"),
        "rps_bye_short": ("Kura · Üst tur", "Bye · Advances"),
        "rps_champion": ("ARENANIN ŞAMPİYONU", "ARENA CHAMPION"),
        "rps_champion_detail": ("{count} oyuncu arasından kupayı alan isim.", "The cup winner out of {count} players."),
        "rps_replay": ("Yeniden meydan oku", "Play another tournament"),
        "rps_edit_players": ("Kadroyu düzenle", "Edit roster"),
        "rps_error": ("İşlem tamamlanamadı. Tekrar dene veya lobiye dön.", "Couldn’t complete that action. Try again or return to the lobby."),
        "rps_ok": ("Tamam", "OK"),
    ]
}
